### ISSUE TITLE
Unresolved reference 'goals' 

### ISSUE THREAD

**Issue by wunglee** [UMass-Foundation-Model/Co-LLM-Agents#10]
https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/MCTS/MCTS.py#L536

https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/MCTS/MCTS.py#L546

these two 'goal' not found

**Comment by Icefoxzhx** [comment]
These functions are deprecated and shouldn't be used. We've cleaned these now. Sorry for the inconvenience.
