### ISSUE TITLE
About hardware configuration

### ISSUE THREAD

**Issue by VitaLemonTea1** [UMass-Foundation-Model/Co-LLM-Agents#16]
could you please tell me the hardware configuration and training time?

**Comment by Icefoxzhx** [comment]
We did most experiments with a single NVIDIA GeForce RTX 2080 SUPER 8G GPU. Notably, our proposed method is mostly training-free, and the only training part is fine-tuning the mask-rcnn model for perception, which we did separately with a single NVIDIA GeForce RTX 2080ti 12G GPU.
