### ISSUE TITLE
tdw_mat

### ISSUE THREAD

**Issue by ramkumarkoppu** [UMass-Foundation-Model/Co-LLM-Agents#17]
Hi,

As per the README, when I ran `./scripts/test_LMs-gpt-4.sh` in the tdw_mat I see this unity window 
![image](https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/30557120/1e85853a-e013-4f9a-832a-93ad0b28aa24)
which is very small for me to findout what's in it. how to have a full window of this graphics?
this was ran on the Ubuntu with Nvidia GPU.

**Comment by Icefoxzhx** [comment]
Hi, there is a parameter in the script to control the window size: "--screen_size", you can try to adjust this to fit your pc.
