### ISSUE TITLE
Couldn't launch the linux_exec.v2.3.0 environment.

### ISSUE THREAD

**Issue by Alicia0728** [UMass-Foundation-Model/Co-LLM-Agents#18]
Hi,

When I tried to run experiments in the folder /cwah/scripts(e.g., ./scripts/symbolic obs llm llm.sh), I got an error saying "couldn't launch the linux_exec.v2.3.0 environment".
<img width="929" alt="Screenshot 2024-03-17 at 15 33 38" src="https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/135338460/fdb6379e-f144-43ad-a33c-a70f06ced20a">
And I organized the folders as required:
![WechatIMG166](https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/135338460/b139cc10-6b58-4dfc-aa21-a840b53063dd)

Is it because I'm using MacOS?

Thank you:)

**Comment by Icefoxzhx** [comment]
Yes, this may be caused by the different OS you're using. I'd suggest you go to Virtualhome's official repo to check for any option for running it on MacOS.
