### ISSUE TITLE
when i reproduce the code, the code is always stopped by the problem:  idex out of bounds

### ISSUE THREAD

**Issue by jliu4ai** [UMass-Foundation-Model/Co-LLM-Agents#21]
File "/home/jie/newdisk/AIAgent/CoELA/tdw_mat/tdw-gym/lm_agent.py", line 768, in act
    self.get_new_object_list()
  File "/home/jie/newdisk/AIAgent/CoELA/tdw_mat/tdw-gym/lm_agent.py", line 251, in get_new_object_list
    if self.object_map[i, j] == 0:
IndexError: index 132 is out of bounds for axis 1 with size 120

**Comment by Icefoxzhx** [comment]
Could you provide more details on the system you're using? And how to reproduce this bug? Thanks

**Comment by jliu4ai** [comment]
<img width="335" alt="Screenshot 2024-04-05 at 21 11 09" src="https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/113556433/179c613f-fbdf-412a-ab9c-258dfcd02fe3">
I am running on unbuntu, i guess it is because the map size you set is (240, 120) in the file lm_agent.py, some of the index is bigger than 120.

**Comment by StigLidu** [comment]
Thank you for your description. To help us investigate this issue more effectively, please try removing the `--no_save_img` hyperparameter from your script and run it again. This change should allow the map images to be saved in the following directory structure: `{output_dir}/{experiment_name}/{run_id}/{episode}/Images/{agent_id}`.

Could you please provide the map images after making this change? This will help us determine if there's an environmental issue or a potential bug in the repository.

**Comment by zulihit** [comment]
Hi, I would like to inquire when you reproduce the author's project, if your program is running on a local Linux computer or a remote Linux server. If I use a remote Linux server, may I not be able to see the visual interface.
