### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by jliu4ai** [UMass-Foundation-Model/Co-LLM-Agents#22]
Hi， could you please tell me the inference time for tdw? On my desktop, it takes around 50 hours, is it normal?

**Comment by Icefoxzhx** [comment]
Could you provide more details on the question of "inference time for tdw"?
Taking around 50 hours for one episode does not look normal. Could u check if the GPU is indeed in use? (e.g. check nvidia-smi to see if TDW takes around 1g mem)

**Comment by jliu4ai** [comment]
thanks for the response. there are 24 episodes in tdw, each of them takes around 2 hours to infer, is this a normal inference speed?

**Comment by StigLidu** [comment]
Running TDW on GPU is much faster than that on CPU. Our experiment ran on an RTX2080, which takes about 20-30 minutes to finish an episode.

**Comment by nchuly** [comment]
same problem，looks like it takes more than 10 hours to load one episode ! could anyone help me?

**Comment by Rhoslynnn** [comment]
same，baseline is very quick but LLM agent is super slow

**Comment by qingxiangjia** [comment]
> 在GPU上运行TDW比在CPU上运行快得多。我们的实验是在RTX2080显卡上运行的，完成一集游戏大约需要20-30分钟。
您好我想问一下您使用的是什么分辨率呀，这个速度很明显和分辨率有关
