### ISSUE TITLE
index out of bound

### ISSUE THREAD

**Issue by jliu4ai** [UMass-Foundation-Model/Co-LLM-Agents#23]
There are some errors caused by out of bound index. I cannot figure it out why it is, are there some important hyperparameters that the author should mention to prevent such errors?

<img width="869" alt="Screenshot 2024-04-06 at 09 51 02" src="https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/113556433/89a01811-5b28-4906-995f-afbc7f3857dd">

**Comment by StigLidu** [comment]
We have implemented updates to the navigation module of agents in the `ThreeDWorld Multi-Agent Transport environment` to address the navigation issues.

Please check if the issue still occurs with this update. If you notice any unusual behavior, do let us know.
