### ISSUE TITLE
Agents go through walls and go to outside of all rooms

### ISSUE THREAD

**Issue by jliu4ai** [UMass-Foundation-Model/Co-LLM-Agents#24]
Sometimes the agents can go through the wall, and stay outside of the rooms, this is not correct for the current code. which parameters should  i set to avoid such problem?
![Uploading Screenshot 2024-04-06 at 17.36.23.png…]()

**Comment by jliu4ai** [comment]
<img width="349" alt="Screenshot 2024-04-06 at 17 36 23" src="https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/113556433/8abc8bb7-68a3-442b-99f0-6b1315b19ee9">

**Comment by jyao97** [comment]
Hi @jliu4ai , have you successfully tackled this issue? I am facing the same problem.

**Comment by StigLidu** [comment]
We have implemented updates to the navigation module of agents in the `ThreeDWorld Multi-Agent Transport environment` to address the navigation issues.

Please check if the issue still occurs with this update. If you notice any unusual behavior, do let us know.
