### ISSUE TITLE
Is there anyone really run this program successfully ?

### ISSUE THREAD

**Issue by ZiyiLiubird** [UMass-Foundation-Model/Co-LLM-Agents#6]
I tried nearly every possible method to fix the error "XDG_RUNTIME_DIR not set in the environment." and "unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=6310): Read timed out. (read timeout=30)" but failed.

**Comment by zhangliyun9120** [comment]
same error, no one works

**Comment by Icefoxzhx** [comment]
Sorry for the late reply.
This issue may be caused by a version conflict with the VirtualHome executable. 
We have provided the new version [here](https://drive.google.com/file/d/1JTrV5jdF-LQVwY3OsV3Jd3r6PRghyHBp/view?usp=sharing) and updated the readme.
Hope it helps.

**Comment by asx568** [comment]
hello there, I now meet the seem problem, but it seems that the above file does not exist...
