### ISSUE TITLE
Unresolved reference 'Random_agent'

### ISSUE THREAD

**Issue by wunglee** [UMass-Foundation-Model/Co-LLM-Agents#7]
https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/testing_agents/data_collection_agent.py#L97C74-L97C74

Unresolved reference 'Random_agent'

**Comment by Icefoxzhx** [comment]
These functions are deprecated and shouldn't be used. We've cleaned these now.
