### ISSUE TITLE
Unresolved reference 'utils_rl_agent'

### ISSUE THREAD

**Issue by wunglee** [UMass-Foundation-Model/Co-LLM-Agents#8]
https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/envs/envs.py#L33C1-L33C22

Unresolved reference 'utils_rl_agent'

**Comment by Icefoxzhx** [comment]
These functions are deprecated and shouldn't be used. We've cleaned these now.
