### ISSUE TITLE
Unresolved reference 'apartment' 

### ISSUE THREAD

**Issue by wunglee** [UMass-Foundation-Model/Co-LLM-Agents#9]
https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/gen_data/init_goal_setter/init_goal_base.py#L468C28-L468C28

https://github.com/UMass-Foundation-Model/Co-LLM-Agents/blob/2c3a5f02ed4f2b45751605511121b26291c777d5/envs/cwah/gen_data/init_goal_setter/init_goal_base.py#L492

these two line:Unresolved reference 'apartment'

**Comment by Icefoxzhx** [comment]
These functions are deprecated and shouldn't be used. We've cleaned them now.
